/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 ../public/Eye.glb 
*/

import React, { forwardRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default forwardRef(function Model(props, ref) {
  const { nodes, materials } = useGLTF('/Eye.glb')
  return (
    <group {...props} dispose={null} ref={ref}>
      <group scale={1.04}>
        <mesh geometry={nodes.Sphere007.geometry} material={materials['Eye.Shader']} />
        <mesh geometry={nodes.Sphere007_1.geometry} material={materials['Glass.Eye']} />
      </group>
    </group>
  )
})

useGLTF.preload('/Eye.glb')
